apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-kubeconfig
  namespace: jenkins
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
      - name: in-cluster
        cluster:
          certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          server: https://kubernetes.default.svc
    contexts:
      - name: jenkins
        context:
          cluster: in-cluster
          namespace: app
          user: jenkins
    current-context: jenkins
    users:
      - name: jenkins
        user:
          tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
